---
all:
  hosts:
    zabbix-srv:
      ansible_host: 192.168.7.126

    zabbix-web:
      ansible_host: 192.168.7.127

    zabbix-db:
      ansible_host: 192.168.7.250

    zabbix-proxy:
      ansible_host: 192.168.7.251

    ubuntu:
      ansible_host: 192.168.7.128
  children:
    zabbix_all:
      hosts:
        zabbix-server:
        zabbix-web:
        zabbix-db:
        zabbix-proxy:
