---
- name: Install system required packages
  ansible.builtin.apt:
    name: gpg
    update_cache: yes
    state: present

- name: Add apt key for PostgreSQL repo
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL repo
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
    state: present
    filename: pgdg

- name: Install PostgreSQL DB and another required packages
  ansible.builtin.apt:
    name:
      - postgresql-13
      - iptables
      - python3-psycopg2
      - sudo
    update_cache: yes
    state: present

- name: Set listen IP of PostgreSQL DB
  ansible.builtin.lineinfile:
    path: /etc/postgresql/13/main/postgresql.conf
    regexp: '^listen_addresses ='
    line: listen_addresses = '{{ zbx_db_host }}, 127.0.0.1'
    insertbefore: '^#listen_addresses'
    state: present
    backup: yes

- name: Grant user access to zabbix databases from all hosts using peer authentication
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: host
    source: "{{ pg_sql_allowed_ip }}"
    users: "{{ zbx_db_user }}"
    databases: '{{ zbx_db_name }}, {{ zbx_proxy_db_name }}'
    method: md5

- name: Enable and start PostgreSQL DB
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Ensure a en_US.UTF-8 locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
