---
- name: Install Zabbix repo
  ansible.builtin.dnf:
    name: 'https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm'
    state: present

- name: Install zabbix agent package
  ansible.builtin.dnf:
    name:
      - logrotate
      - zabbix-agent
    update_cache: yes
    state: present
